### ISSUE TITLE
Is there a way to run it on macos arm64 ?

### ISSUE THREAD

**Issue by thegodone** [reymond-group/MultiStepRetrosynthesisTTL#2]
I have used the 1.13.1 torch version and install other dependencies:

I have the following error : 
```
(MultiStepRetro_ENZ) tgg@macbook-pro MultiStepRetrosynthesisTTL % retrosynthesis --config configs/config_example.yaml

Traceback (most recent call last):
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/bin/retrosynthesis", line 8, in <module>
    sys.exit(main())
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/ttlretro/run_multistep_retrosynthesis.py", line 207, in main
    run_retrosynthesis(args.config)
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/ttlretro/run_multistep_retrosynthesis.py", line 193, in run_retrosynthesis
    _, _ = multi_step_retro_predictions.multistep_search(
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/ttlretro/multi_step_retro_predictions.py", line 536, in multistep_search
    predictions, _ = self.init_predictions_dataframe(target_cpd=target_cpd)
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/ttlretro/multi_step_retro_predictions.py", line 480, in init_predictions_dataframe
    predictions, df_prediction_backup = self.make_single_retropredictions.Execute_Retro_Prediction(
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/ttlretro/single_step_retro/single_step_retro.py", line 531, in Execute_Retro_Prediction
    list_retro_USPTO = self._get_list_tags(
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/ttlretro/single_step_retro/single_step_retro.py", line 442, in _get_list_tags
    list_retro += self.get_AutoTags(target=target, ini_smiles=SMILES, AutoTagging_Beam_Size=AutoTagging_Beam_Size, Model=AutoTagModel)
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/ttlretro/single_step_retro/single_step_retro.py", line 256, in get_AutoTags
    list_retro_auto_tag, _ = self.Execute_Prediction([self.smi_tokenizer(target)], Model_path=Model, beam_size=AutoTagging_Beam_Size)
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/ttlretro/single_step_retro/single_step_retro.py", line 187, in Execute_Prediction
    trsl.translate(opt)
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/onmt/bin/translate.py", line 25, in translate
    translator.translate(
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/onmt/translate/translator.py", line 370, in translate
    batch_data = self.translate_batch(
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/onmt/translate/translator.py", line 567, in translate_batch
    return self._translate_batch_with_strategy(batch, src_vocabs,
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/onmt/translate/translator.py", line 700, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/Users/tgg/miniforge3/envs/MultiStepRetro_ENZ/lib/python3.8/site-packages/onmt/translate/beam_search.py", line 212, in advance
    torch.div(self.topk_ids, vocab_size, out=self._batch_index)
RuntimeError: result type Float can't be cast to the desired output type Long

```

**Comment by DavKre** [comment]
The required OpenNMT version for this repo has been updated to support torch 1.13.1, it should now run on macOS.
